// tslint:disable: no-import-side-effect
import './component/a.test.ts'
import './component/app.test.ts'
import './component/head.test.ts'
import './component/header.test.ts'
import './component/nav.test.ts'
import './lib/cancel.test.ts'
import './lib/fetch-content.test.ts'
import './lib/marked-html.test.ts'
import './lib/parse-content.test.ts'
import './manager/base.test.ts'
import './reducer/navs.test.ts'
import './store/content.test.ts'
import './store/navs.test.ts'
import './store/route.test.ts'
